// <auto-generated />
using System;
using ColoradoGroupEvaluation.Infra.Base.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColoradoGroupEvaluation.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250908211432_UpdatedModel")]
    partial class UpdatedModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ColoradoGroupEvaluation.Shared.Models.Cliente.Domain.Cliente", b =>
                {
                    b.Property<int>("CodigoCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CodigoCliente"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Complemento")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("longtext");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoPessoa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsercao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CodigoCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ColoradoGroupEvaluation.Shared.Models.Telefone.Domain.Telefone", b =>
                {
                    b.Property<int>("CodigoTelefone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CodigoTelefone"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ClienteCodigoCliente")
                        .HasColumnType("int");

                    b.Property<int>("CodigoCliente")
                        .HasColumnType("int");

                    b.Property<int>("CodigoTipoTelefone")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime");

                    b.Property<string>("NumeroTelefone")
                        .HasColumnType("longtext");

                    b.Property<string>("Operadora")
                        .HasColumnType("longtext");

                    b.Property<int?>("TipoTelefoneCodigoTipoTelefone")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioInsercao")
                        .HasColumnType("longtext");

                    b.HasKey("CodigoTelefone");

                    b.HasIndex("ClienteCodigoCliente");

                    b.HasIndex("TipoTelefoneCodigoTipoTelefone");

                    b.ToTable("Telefones");
                });

            modelBuilder.Entity("ColoradoGroupEvaluation.Shared.Models.TipoTelefone.Domain.TipoTelefone", b =>
                {
                    b.Property<int>("CodigoTipoTelefone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CodigoTipoTelefone"));

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime");

                    b.Property<string>("DescricaoTipoTelefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioInsercao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CodigoTipoTelefone");

                    b.ToTable("TiposTelefone");
                });

            modelBuilder.Entity("ColoradoGroupEvaluation.Shared.Models.Telefone.Domain.Telefone", b =>
                {
                    b.HasOne("ColoradoGroupEvaluation.Shared.Models.Cliente.Domain.Cliente", "Cliente")
                        .WithMany("Telefones")
                        .HasForeignKey("ClienteCodigoCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ColoradoGroupEvaluation.Shared.Models.TipoTelefone.Domain.TipoTelefone", null)
                        .WithMany("Telefones")
                        .HasForeignKey("TipoTelefoneCodigoTipoTelefone");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ColoradoGroupEvaluation.Shared.Models.Cliente.Domain.Cliente", b =>
                {
                    b.Navigation("Telefones");
                });

            modelBuilder.Entity("ColoradoGroupEvaluation.Shared.Models.TipoTelefone.Domain.TipoTelefone", b =>
                {
                    b.Navigation("Telefones");
                });
#pragma warning restore 612, 618
        }
    }
}
